#!/bin/bash

echo "Running ktlintFormat before commiting code..."

# stash the current index with unstaged changes
git stash -q --keep-index

# check for any formatting errors in the staged changes
./gradlew ktlintFormat

RESULT=$?

git stash pop -q

# if result is nonzero exit the process, as there were some failures
[ $RESULT -ne 0 ] && exit 1

# get staged kotlin files (not deleted)
CHANGED_KOTLIN_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

if [ -z "$CHANGED_KOTLIN_FILES" ]; then
    echo "No Kotlin staged files found"
    exit 0
fi;

echo "Formatting these files: "
echo "$CHANGED_KOTLIN_FILES"

./gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_KOTLIN_FILES"

echo "$CHANGED_KOTLIN_FILES" | while read -r file; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done
echo "Completed ktlintFormat pre-commit"